name: drivewise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  image_picker: ^1.1.2  # Removed commented version
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.35.0
  permission_handler: ^11.3.1
  lottie: ^3.2.0
  flutter_launcher_icons: ^0.14.3  # Consider upgrading to the latest version
  lucide_icons: ^0.257.0
  flutter_local_notifications: ^18.0.1
  http: ^1.3.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  http_parser: ^4.0.2
  timezone: ^0.10.0
  google_maps_flutter: ^2.10.1
  geocoding: ^3.0.0
  google_places_flutter: ^2.1.0
  geolocator: ^13.0.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/drivewise_app.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Check if a newer version is available

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile_placeholder.png
    - assets/images/logo.png
    - assets/images/logo3d.png
    - assets/animations/car_animation.json
    - assets/animations/welcome_car.json
    - assets/images/car.png
    - assets/images/google_logo.png
    - assets/images/engine_oil.jpg.png
    - assets/images/toyota.png
    - assets/images/valvoline.png
    - assets/images/lukoil.png
    - assets/images/mobil.png
    - assets/images/caltex.png
    - assets/images/transmission_oil.png
    - assets/images/oil_filters.jpg
    - assets/images/tyres.jpg
    - assets/images/break_fluid.png
    - assets/images/splash_background.jpg
    - assets/images/toyota_motor_oil.png
    - assets/images/Toyota_WS_AT_Fluid.png
    - assets/images/oil_filter_90915-10003.png
